version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_backplane
    ports:
      - "6379:6379"

  notification-api:
    build:
      context: .
      dockerfile: src/Notification.Api/Dockerfile
    ports:
      - "5001-5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnection=redis:6379
    depends_on:
      - redis
    # Bu komut 3 ayrı instance çalıştırılmasını sağlar
    deploy:
      replicas: 3